import { UserLookupLogs } from "@/components/etl/UserLookupLogs";
import { PageHeader } from "@/components/PageHeader";
import { getQueryClient } from "@/lib/getQueryClient";
import { getLookupLogsOptions } from "@/lib/queryOptions/lookup";
import { dehydrate, HydrationBoundary } from "@tanstack/react-query";

const LookupLogsPage = async () => {
  const queryClient = getQueryClient();
  await queryClient.prefetchQuery(getLookupLogsOptions());

  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      <div className="flex flex-1 flex-col h-full">
        <PageHeader
          description="Logs Generated by importing Transactions"
          title="Lookup Logs"
        />
        <div className="h-full py-6">
          <UserLookupLogs />
        </div>
      </div>
    </HydrationBoundary>
  );
};
export default LookupLogsPage;
